server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.j93065772.myjino.ru:3306/j93065772
    username: j93065772
    password: crytek236

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicTinder: TRACE

auth:
  token:
    secret: ljhdslghiopbmispvgspmvgjcaqdfsojdh1uh980fudh178rfh234897fh92378f8
    auth-expiration: 36000000000
    refresh-expiration: 365000000000
